// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// Rcpp_labels_dendrogram
std::vector<std::string> Rcpp_labels_dendrogram(List x);
RcppExport SEXP RcppDend_Rcpp_labels_dendrogram(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    List x = Rcpp::as<List >(xSEXP);
    std::vector<std::string> __result = Rcpp_labels_dendrogram(x);
    return Rcpp::wrap(__result);
END_RCPP
}
// Rcpp_count_leaves
int Rcpp_count_leaves(List data);
RcppExport SEXP RcppDend_Rcpp_count_leaves(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    List data = Rcpp::as<List >(dataSEXP);
    int __result = Rcpp_count_leaves(data);
    return Rcpp::wrap(__result);
END_RCPP
}
