# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rcpp_labels_dendrogram <- function(x) {
    .Call('RcppDend_Rcpp_labels_dendrogram', PACKAGE = 'RcppDend', x)
}

Rcpp_count_leaves <- function(data) {
    .Call('RcppDend_Rcpp_count_leaves', PACKAGE = 'RcppDend', data)
}

